SELECT 
	MOV.NRO_PEDIDO,
	MOV.FECHA,
	SOL.DENOM_CORTA AS SOLICITANTE,
	ARE.DENOM_CORTA AS AREA_SOLICITANTE,
	MOV.DESCRIPCION,
	MOV.DESTINO,
	MOV.REF_DOC_ASOCIADO,
	MOV.REF_PED_ANTERIOR,
	CASE MOV.SITUACION 
		WHEN 'CUMP' THEN 'CUMPLIDO'
		WHEN 'PARC' THEN 'PARCIAL CUMPLIDO'
		WHEN 'LICI' THEN 'LICITACION'
		WHEN 'ADJU' THEN 'ADJUDICADO'
		ELSE 'PENDIENTE'
	END AS SITUACION
	
FROM 
PEDIDO_MOVIMIENTO MOV 
LEFT OUTER JOIN PEDIDO_DEPENDENCIA SOL ON MOV.SOLICITANTE_ID = SOL.ID
LEFT OUTER JOIN PEDIDO_DEPENDENCIA ARE ON MOV.AREA_SOLICITANTE_ID = ARE.ID
WHERE 1=1
AND  (CAST(TO_CHAR(FECHA,'YYYY') AS INT) IN ($P!{P_ANHO}) OR $P{P_ANHO}  IS NULL) 
AND  (MOV.SITUACION IN ($P!{P_SITUACION}) OR $P{P_SITUACION}  IS NULL) 
AND  (MOV.SOLICITANTE_ID IN ($P!{P_SOLICITANTE_ID}) OR $P{P_SOLICITANTE_ID}  IS NULL) 
AND  (MOV.AREA_SOLICITANTE_ID IN ($P!{P_AREA_SOLICITANTE_ID}) OR $P{P_AREA_SOLICITANTE_ID}  IS NULL) 
AND  (MOV.FECHA >= TO_DATE($P{P_FECHA_DESDE},'YYYY-MM-DD') OR $P{P_FECHA_DESDE} IS NULL) 
AND  (MOV.FECHA <= TO_DATE($P{P_FECHA_HASTA},'YYYY-MM-DD') OR $P{P_FECHA_HASTA} IS NULL) 
ORDER BY MOV.FECHA, MOV.NRO_PEDIDO 
